name: Publish a release

on:
  push:
    tags:
      - v*

env:
  FOO: bar

jobs:
  deployTest:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Deploy
        run: echo I am deploying test!
  deployProd:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy
        run: echo I am deploying production!